#!/usr/bin/env python

''' A simple Tkinter graphical user interface for reading DMARC XML files. '''

import src.dmarcreport as dr


if __name__ == '__main__':

    WIN = dr.DmarcReport()
    WIN.mainloop()
