#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File name: dmarcreport.py

'''
Dmarc Report.

Copyright 2016, Hans Åge Martinsen <hamartin@moshwire.com>
'''

from src.dmarcreport import DmarcReport


if __name__ == '__main__':
    DmarcReport().run()
